#!/bin/zsh -euf

CMD="$CONFIGURATION_BUILD_DIR/$PRODUCT_NAME"

TEST_OUTPUT_DIR="$DERIVED_FILES_DIR/TestOutput"
rm -rf "$TEST_OUTPUT_DIR"
mkdir -p "$TEST_OUTPUT_DIR"

echo "Test output $TEST_OUTPUT_DIR"

# N.B. -q Turns off multiple key/value pairs warning.
# Our tests intentionally have data with multiple key/value pairs; we don't want to see this warning during a normal build.
/usr/bin/genstrings -q -o "$TEST_OUTPUT_DIR" Tests/input.m

for output in "$TEST_OUTPUT_DIR/"*.strings; do
  test_name="$output:t"
  expected_output="Tests/${test_name}"
  #echo expected_output="$expected_output"
  $CMD "$output"
  diff "$output" "$expected_output"
done

# Update the marker file for the build system, indicating that everything was OK for the current set of inputs.
touch "$SCRIPT_OUTPUT_FILE_0"
