#!/bin/zsh -eu

export OBASSERT_NO_BANNER=1
export OB_SUPPRESS_SUPPRESSED_CONFLICT_COUNT=1
export NSDeallocateZombies=NO
export NSZombieEnabled=YES
export OFAutomaticallyTrustAllHosts=YES
#export OFXSyncDebug=1
export OFSAccountRemoteBaseURL=https://crispy.local:8001/
export OFSAccountUsername=test
export OFSAccountPassword=password
#export OBASSERT_TIME_TO_WAIT=60

OTEST=`xcrun -find otest`

# xcrun requires gc currently
export OBJC_DISABLE_GC=YES

# TODO: Collect each run's log, run time, and status. Report number of runs so far.
LOG_DIR=/tmp/pound-logs
rm -rf "$LOG_DIR"
mkdir "$LOG_DIR"

counter=0
while true; do
    LOG_FILE="$LOG_DIR/$counter.log"
#    -SenTest OFXDocumentEditTestCase/testTransferProgress
    $OTEST -SenTest OFXDocumentEditTestCase/testTransferProgress ~/Library/Developer/Xcode/DerivedData/OmniPresence-*/Build/Products/Debug/OFXUnitTests.octest |& tee "$LOG_FILE" | grep "^Executed"
    ((counter=$counter+1))
done

# TODO: Allow tests to include their pid in the local and remote paths. Could then run multiple instances of the test in parallel (which would pound the web server too...)
