// Copyright 2002-2016 Omni Development, Inc. All rights reserved.
//
// This software may only be used and reproduced according to the
// terms in the file OmniSourceLicense.html, which should be
// distributed with this project and can also be found at
// <http://www.omnigroup.com/developer/sourcecode/sourcelicense/>.
//
// $Id$

#import <AppKit/NSWindowController.h>
#import <OmniAppKit/OAToolbar.h>

NS_ASSUME_NONNULL_BEGIN

@class OAToolbar;
@class NSToolbarItem;
@class NSBundle, NSDictionary;

@protocol OAToolbarHelper

// A path suffix that should be on the toolbar items returned from `allowedItems`
- (NSString *)itemIdentifierExtension;

// The identifier of a toolbar item identifier in a .toolbar file where the various labels can have '%@' as a placeholder for the item name. This template gets replaced by the items generated by -allowedItems.
- (NSString *)templateItemIdentifier;

// The list of item identifiers provided by this helper. The identifiers should be <name>.<extension>, where the name will be passed into the format strings in the template specified by templateItemIdentifier.
- (NSArray<NSString *> *)allowedItems;

- (nullable NSToolbarItem *)finishSetupForToolbarItem:(NSToolbarItem *)item toolbar:(NSToolbar *)toolbar willBeInsertedIntoToolbar:(BOOL)willInsert;

@end

@interface OAToolbarWindowController : NSWindowController <OAToolbarDelegate>

+ (void)registerToolbarHelper:(NSObject <OAToolbarHelper> *)helperObject;
+ (NSBundle *)toolbarBundle;
+ (Class)toolbarClass;
+ (Class)toolbarItemClass;

- (OAToolbar *)toolbar;
- (void)createToolbar;
- (BOOL)isCreatingToolbar;
- (nullable NSDictionary *)toolbarInfoForItem:(NSString *)identifier;
- (nullable NSDictionary *)localizedToolbarInfoForItem:(NSString *)identifier;

// implement in subclasses to control toolbar
- (NSString *)toolbarConfigurationName; // file name to lookup .toolbar plist
- (NSString *)toolbarIdentifier; // identifier used for preferences - defaults to configurationName if unimplemented
- (BOOL)shouldAllowUserToolbarCustomization;
- (BOOL)shouldAutosaveToolbarConfiguration;
- (NSToolbarDisplayMode)defaultToolbarDisplayMode;
- (NSDictionary *)toolbarConfigurationDictionary; // Used when -shouldAutosaveConfiguration returns NO

@end

NS_ASSUME_NONNULL_END
