#!/bin/zsh -euf
#
# Copyright 2010 Omni Development, Inc.  All rights reserved.
#
# This software may only be used and reproduced according to the
# terms in the file OmniSourceLicense.html, which should be
# distributed with this project and can also be found at
# <http://www.omnigroup.com/developer/sourcecode/sourcelicense/>.
#
# $Id$


#
# Xcode doesn't go out of its way to make it easy to figure out which source
# files were a part of which target.
#

SCRIPTS_DIR=$0:h

source_files=()
$SCRIPTS_DIR/ListSourceFilesInTarget "$TARGET_NAME" c,m "$PROJECT_FILE_PATH" | while read f; do
   source_files+=($f)
done

# Build the strings file(s) into a separate directory so we can avoid mucking with timestamps in the build output unless needed (see below).

STRINGS_DIR="$DERIVED_FILES_DIR/BuildStringsFromTarget-$TARGET_NAME"
if [ -d "$STRINGS_DIR" ]; then
  rm -rf "$STRINGS_DIR"
fi

mkdir -p "$STRINGS_DIR"
cd "$STRINGS_DIR"

mkdir English.lproj
if [ $#source_files -gt 0 ]; then
	/usr/bin/genstrings -u -q -o English.lproj $source_files
fi

# Sort and translate common ASCII sequences into Unicode.
FIX_STRINGS_FILE="$BUILD_DIR/$CONFIGURATION"/FixStringsFile
if [ -x "$FIX_STRINGS_FILE" ]; then
    # TODO: Make this handle the case where there are no strings files emitted. Right now we only run this script if we know there will be one or more.
    for sfile in English.lproj/*.strings; do
    	"$FIX_STRINGS_FILE" "$sfile"
    done
else
    # Probably a local build from Xcode rather than our build scripts.
    echo "FixStringsFile isn't built -- skipping (this will result in ASCII to Unicode conversions not happening)"
fi

# Publish the results for the app to pick up.
RESOURCE_DIR="$CONFIGURATION_BUILD_DIR/Resources/$PRODUCT_NAME"

# Make sure not to re-copy if only the source timestamp has changed. That will invalidate timestamps that may cause further copying into the app bundle. This in turn can invalidate signing, which is very annoying if we are doing incremental device builds.
mkdir -p "$RESOURCE_DIR"
rsync -v --recursive --checksum English.lproj/ "$RESOURCE_DIR/English.lproj/"
