#!/bin/zsh
#
# $Id$

setopt ERR_EXIT
set -u

# Check the version of OmniGroup
cd $(dirname $0) # This is OmniGroup/Scripts
cd .. # This is OmniGroup

PN="$0:t"
Usage () {
    echo >&2 "Usage: $PN [options] build_directory"
    echo >&2 "  Options:"
    echo >&2 "    --help                - show the usage"
    echo >&2 "    --build-versions-txt  - build Versions.txt"
    echo >&2 "    --force               - force rebuild of SVNVersion.h"
    exit 1
}

# If we are running for the public source, which is not in svn, quitely exit
if [ -d .git ]; then
    exit;
fi

FORCE_REBUILD=
GENERATE_VERSIONS_TXT=NO

while [ $# -gt 0 ]
do
    case "$1" in
        --)
            shift
            break
            ;;
        --help|-h)
            Usage
            ;;
        --build-versions-txt)
            GENERATE_VERSIONS_TXT=YES
            ;;
        --force)
            FORCE_REBUILD=YES
            ;;
        --*)
            Usage
            ;;
        *)
            break
            ;;
    esac
    shift
done

# This will typically be CONFIGURATION_BUILD_DIR from Xcode. Version.txt will be placed in this directory and SVNVersion.h will be placed in an 'include' subdirectory
if [ $# -ne 1 ]; then
    Usage
fi
BUILD_DIR="$1"

BUILD_DATE=`TZ=UTC date +"%Y-%m-%dT%H:%M:%S.000Z"`
REBUILD=YES

SVNURL=`svn info --xml . | xpath '/info/entry/url/text()' 2>& /dev/null`
if [ "$SVNURL" != "" ]; then
    if [ -n "${OMNI_VERSIONS-}" -a -f "${OMNI_VERSIONS-}" ]; then
        SVNREVISION=$(awk '/Revision: / {print $2}' $OMNI_VERSIONS)
    else
        SVNREVISION=`svn info --xml . | xpath 'string(/info/entry/@revision)' 2>& /dev/null`
        CACHED_REVISION=""
        if [ -f "$BUILD_DIR/include/SVNVersion.h" ]; then
            CACHED_REVISION=`awk -v IFS=' ' '/^#define SVNREVISION / {print $3}' "$BUILD_DIR/include/SVNVersion.h"`
        fi
        if [ "$CACHED_REVISION" = "$SVNREVISION" ]; then
            REBUILD=$FORCE_REBUILD
        fi
    fi
else
    SVNURL="not svn"
    SVNREVISION=0
fi

mkdir -p "$BUILD_DIR/include"

if [ "$REBUILD" = "YES" ]; then
    (
        echo -n "#define SVNVERSION @\""
        echo -n $SVNURL
        echo -n "@"
        echo -n $SVNREVISION
        echo "\""
    
        echo "#define SVNREVISION $SVNREVISION"
        echo "#define SVNURL $SVNURL"
        echo "#define BUILD_DATE @\"$BUILD_DATE\""
    ) > "$BUILD_DIR/include/SVNVersion.h"
fi

if [ "$GENERATE_VERSIONS_TXT" = "YES" ]; then
    mkdir -p "$BUILD_DIR"
    if [ -n "${OMNI_VERSIONS-}" -a -f "${OMNI_VERSIONS-}" ]; then
        cp -p "$OMNI_VERSIONS" "$BUILD_DIR/Versions.txt"
    else
        (
            echo "Build details:"
            echo ""
            echo "Product: [development build]"
            echo "Date:" `date +"%Y-%m-%d %H:%M:%S %z"`
            echo "Builder: $USER"
            echo "Host:" `hostname`
            echo "Revision: $SVNREVISION"
        ) > "$BUILD_DIR/Versions.txt"
    fi
fi
