#!/bin/zsh
#
# $Id$

setopt ERR_EXIT
set -u

# Check the version of OmniGroup
cd $(dirname $0) # This is OmniGroup/Scripts
cd .. # This is OmniGroup

PN="$0:t"
Usage () {
    echo >&2 "Usage: $PN [options] build_directory"
    echo >&2 "  Options:"
    echo >&2 "    --help                - show the usage"
    echo >&2 "    --build-versions-txt  - build Versions.txt"
    echo >&2 "    --golang              - build svnversion.go"
    echo >&2 "    --force               - force rebuild of SVNVersion.h"
    exit 1
}

# If we are running for the public source, which is not in svn, quitely exit.
if [ ! -d ../.svn ]; then
    exit;
fi

FORCE_REBUILD=
GENERATE_VERSIONS_TXT=NO
GOLANG=NO
: ${SVN:=svn}

while [ $# -gt 0 ]
do
    case "$1" in
        --)
            shift
            break
            ;;
        --help|-h)
            Usage
            ;;
        --build-versions-txt)
            GENERATE_VERSIONS_TXT=YES
            ;;
        --golang)
            GOLANG=YES
            ;;
        --force)
            FORCE_REBUILD=YES
            ;;
        --*)
            Usage
            ;;
        *)
            break
            ;;
    esac
    shift
done

# This will typically be CONFIGURATION_BUILD_DIR from Xcode. Version.txt will be placed in this directory and SVNVersion.h will be placed in an 'include' subdirectory
if [ $# -ne 1 ]; then
    Usage
fi
BUILD_DIR="$1"

OUTPUT_HEADER="$BUILD_DIR/include/SVNVersion.h"
OUTPUT_VERSIONS_TXT="$BUILD_DIR/Versions.txt"
OUTPUT_SVNVERSION_GO="$BUILD_DIR/svnversion.go"

# Don't do the work to rebuild the header/Versions.txt (or check if they need rebuilding) by default. In particular, the `svn info` command takes a little while and slows down incremental builds.
REBUILD=$FORCE_REBUILD
if [ ! -f "$OUTPUT_HEADER" ]; then
    REBUILD="YES"
elif [ "$GENERATE_VERSIONS_TXT" = "YES" -a \! -f "$OUTPUT_VERSIONS_TXT" ]; then
    REBUILD="YES"
elif [ "$GOLANG" = "YES" -a \! -f "$OUTPUT_SVNVERSION_GO" ]; then
    REBUILD="YES"
fi
if [ -z "$REBUILD" ]; then
    exit
fi

BUILD_DATE=`TZ=UTC date +"%Y-%m-%dT%H:%M:%S.000Z"`

SVNURL=`$SVN info --xml . | xpath '/info/entry/url/text()' 2>& /dev/null`
if [ "$SVNURL" != "" ]; then
    if [ -n "${OMNI_VERSIONS-}" -a -f "${OMNI_VERSIONS-}" ]; then
        SVNREVISION=$(awk '/Revision: / {print $2}' $OMNI_VERSIONS)
    else
        SVNREVISION=`$SVN info --xml . | xpath 'string(/info/entry/@revision)' 2>& /dev/null`
    fi
else
    SVNURL="not svn"
    SVNREVISION=0
fi

mkdir -p "$BUILD_DIR/include"

(
    echo -n "#define SVNVERSION @\""
    echo -n $SVNURL
    echo -n "@"
    echo -n $SVNREVISION
    echo "\""

    echo "#define SVNREVISION $SVNREVISION"
    echo "#define SVNURL $SVNURL"
    echo "#define BUILD_DATE @\"$BUILD_DATE\""
) > "$OUTPUT_HEADER"

if [ "$GENERATE_VERSIONS_TXT" = "YES" ]; then
    mkdir -p "$BUILD_DIR"
    if [ -n "${OMNI_VERSIONS-}" -a -f "${OMNI_VERSIONS-}" ]; then
        cp -p "$OMNI_VERSIONS" "$OUTPUT_VERSIONS_TXT"
    else
        (
            echo "Build details:"
            echo ""
            echo "Product: [development build]"
            echo "Date:" `date +"%Y-%m-%d %H:%M:%S %z"`
            echo "Builder: $USER"
            echo "Host:" `hostname`
            echo "Revision: $SVNREVISION"
        ) > "$OUTPUT_VERSIONS_TXT"
    fi
fi

if [ "$GOLANG" = "YES" ]; then
    mkdir -p "$BUILD_DIR"
    (
        echo "package svnversion"
        echo ""
        echo "import ("
        echo "	\"time\""
        echo ")"
        echo ""
        echo "const SVNVersion int = $SVNREVISION"
        echo "const SVNURL string = \"$SVNURL\""
        echo "var BuildDate time.Time = time.Unix(`date +\"%s\"`, 0)"
        echo "const BuildHost string = \"`hostname`\""
        echo "const BuildUser string = \"$USER\""
    ) > "$OUTPUT_SVNVERSION_GO"
fi
