#!/bin/zsh -euf

# Run the right version from our PWD's OmniGroup/Scripts directory if we find this in /usr/omni/bin/Scripts
OMNI_SCRIPT_EXEC_ORIGINAL=$0 . $0:h/OmniScriptsReexec

# Xcode's unit test running script will silently bail unless ACTION is "build".
# Presumably this is to avoid running tests when doing "clean" builds, but it
# also makes "install" builds not run tests. So, we use this script in our build
# phases and lie to the Xcode script about the ACTION.

ACTION=build "${SYSTEM_DEVELOPER_DIR}/Tools/RunUnitTests"
