#!/bin/zsh -euf
#
# Copyright 2010-2011 Omni Development, Inc. All rights reserved.
#
# This software may only be used and reproduced according to the
# terms in the file OmniSourceLicense.html, which should be
# distributed with this project and can also be found at
# <http://www.omnigroup.com/developer/sourcecode/sourcelicense/>.
#
# $Id$

# Run the right version from our PWD's OmniGroup/Scripts directory if we find this in /usr/omni/bin/Scripts
OMNI_SCRIPT_EXEC_ORIGINAL=$0 . $0:h/OmniScriptsReexec

# Xcode's unit test running script will silently bail unless ACTION is "build"
# and TEST_AFTER_BUILD is "YES". Presumably this is to avoid running tests
# when doing "clean" builds, but it also makes "install" builds not run tests.
# So, we use this script in our build phases and lie to the Xcode script
# about the ACTION.
# We want tests to run when manually requested in Xcode (cmd-u -> sets
# TEST_AFTER_BUILD) or when building for release (tinderbox builds use install
# and local Release builds).

if [ "$ACTION" = "install" -o "$CONFIGURATION" = "Release" ]; then
	export ACTION=build
	export TEST_AFTER_BUILD=YES
fi

if [ "$XCODE_VERSION_MAJOR" -lt 0500 ]; then
    "${SYSTEM_DEVELOPER_TOOLS}/RunUnitTests"
else
    "${SYSTEM_DEVELOPER_TOOLS}/RunUnitTests" | sed 's/error:/warning:/' || true
fi
