#!/bin/zsh -f
#
# Copyright 2005, 2008 Omni Development, Inc.  All rights reserved.
#
# This software may only be used and reproduced according to the
# terms in the file OmniSourceLicense.html, which should be
# distributed with this project and can also be found at
# <http://www.omnigroup.com/developer/sourcecode/sourcelicense/>.
#
# $Id$

# At Omni, this is done by a ruby script that figures out the appropriate dependencies for whichever project is passed on the command line and produces the right build order.  But that's overkill for our published source distribution--here, we'll just specify the build order by hand.

if [ -d Nisus/LinkBack ]; then
    echo Nisus/LinkBack/Source
elif [ -d OmniGroup/LinkBack ]; then
    echo OmniGroup/LinkBack/Source
fi

cat << .
OmniGroup/Tools/FixStringsFile
OmniGroup/Frameworks/OmniBase 
OmniGroup/Frameworks/OmniFoundation 
OmniGroup/Frameworks/OmniFileStore
OmniGroup/Frameworks/OmniUnzip
OmniGroup/Frameworks/OmniDataObjects 
OmniGroup/Frameworks/OmniNetworking 
OmniGroup/Frameworks/OmniAppKit 
OmniGroup/Frameworks/OmniQuartz
OmniGroup/Frameworks/OmniInspector 
OmniGroup/Frameworks/OmniSoftwareUpdate 
OmniGroup/Frameworks/OWF 
OmniGroup/Frameworks/OIF 
OmniGroup/Frameworks/OmniSQLite 
OmniGroup/Frameworks/OmniFoundation(OFUnitTests) 
OmniGroup/Frameworks/OmniNetworking(ONUnitTests) 
OmniGroup/Frameworks/OmniAppKit(OAUnitTests) 
.
