#!/bin/zsh -f
#
# Copyright 2005, 2008 Omni Development, Inc.  All rights reserved.
#
# This software may only be used and reproduced according to the
# terms in the file OmniSourceLicense.html, which should be
# distributed with this project and can also be found at
# <http://www.omnigroup.com/developer/sourcecode/sourcelicense/>.
#
# $Id$

# At Omni, this is a big perl script that figures out the appropriate dependencies for whichever project is passed on the command line and produces the right build order.  But that's overkill for our published source distribution--here, we'll just specify the build order by hand.

cat << .
OmniGroup/Frameworks/OmniBase 
OmniGroup/Frameworks/OmniFoundation 
OmniGroup/Frameworks/OmniDataObjects 
OmniGroup/Frameworks/OmniNetworking 
OmniGroup/Frameworks/OmniAppKit 
OmniGroup/Frameworks/OmniInspector 
OmniGroup/Frameworks/OmniSoftwareUpdate 
OmniGroup/Frameworks/OWF 
OmniGroup/Frameworks/OIF 
OmniGroup/Frameworks/OmniSQLite 
OmniGroup/Frameworks/OmniFoundation(OFUnitTests) 
OmniGroup/Frameworks/OmniNetworking(ONUnitTests) 
OmniGroup/Frameworks/OmniAppKit(OAUnitTests) 
.
