#!/bin/zsh -ef

# gdb has no environment variable expansion.  Sad.
INI_FILE=/tmp/$0:t.gdb.$$
(
	#echo set env OBJC_DISABLE_GC=YES
	echo set args $* /Users/Shared/$USER/Source/PROJ/Products/Debug/OFUnitTests.octest
) > $INI_FILE
gdb /Developer/Tools/otest -x $INI_FILE
rm -f $INI_FILE
